### ISSUE TITLE
I think this was causing your caching issue today.

### ISSUE THREAD

**Issue by cburkins** [cburkins/iris-dashboard#49]
@jfb74 
My best guess is that this line was causing your caching issue today.  Rather than force clearing the cache, I think you could have incremented ?v1.01 to ?v1.02 and it might have worked.   Though, I'm a bit puzzled, since that was the first time we loaded up your code on the wall machine, I can't quite figure out how an incorrect version got cached in the first place.....    

https://github.com/cburkins/iris-dashboard/blob/d016eb406872841ebac19f8bff022175409a9834/directives/directives.js#L49

**Comment by jfb74** [comment]
@cburkins good catch. I've read up on this a bit and it's definitely a question which is asked by developers across the angular community (if stack overflow is any indication). Their solutions truly seem to be the addition of a hash value anytime a file name is referenced. This is something that they call "cache busting".

The only slightly cleaner way to do it would be to have a universal hash for all files instead of hard coding it into the string. This is so you don't have to update it manually every time a change is made. This universal hash would be defined at runtime, common examples being the current time or a random generated integer. I believe you're doing something closer to this in the php solution you have in the index file.
