### ISSUE TITLE
Create intercept for non-Chrome browsers

### ISSUE THREAD

**Issue by cburkins** [cburkins/iris-dashboard#5]
This whole application only works in Chrome.  So if IE11 is used to load the page, it should pop up a simple message saying that only Chrome is support.

**Comment by jfb74** [comment]
The dashboard seems to load correctly in Edge on Windows 10.

For IE10/11 the reason why it doesn't load is because you use ES6 style for loops which IE doesn't support 

ES6 for loops
```
for(object in result){
   doSomething(object);
}
```
vs

ES5 style loops 
```
for(var i=0; i < result.length; i++){ 
   var object = result[i];
   doSomething(object);
}
```

There are 2 solutions to this problem:

1.

**Comment by cburkins** [comment]
Chris Flotta is going to love you for this.  He LOVES IE11.     I'll try it out !

**Comment by cburkins** [comment]
Seems like I need to get rid of the string.includes() and array.includes() as well, they seem to also be ES6.   Did you encounter the same ?     I'm not going to lie, it offends me me a tiny bit to get rid of the .includes() methods.   It's so much more readable than the indexOf() equivalent in ES5 (assuming my research is correct).    I'm starting to think I might just make this an ES6-only app.    Do you think you can still create an intercept for ES5 browsers ?   I'm now also starting to test it in Edge as well.   It loads, but the CSS looks off.  Really off.    Let's compare notes tomorrow.

**Comment by jfb74** [comment]
@cburkins I started building something on [chromeRedirectSubdirs](https://github.com/cburkins/iris-dashboard/tree/chromeRedirectSubdirs) which handles the three cases we are looking at. 
1) Edge - Creates a button which auto copies the current page's link to the clipboard (chromerun:// doesn't seem to work in Edge)
2) IE & Other Browser - Creates a button to do a chromerun://
3) Chrome - No change in behavior.

I was really hoping to be able to leverage Angular to do this, but I would have had to dynamically load your libraries only if the user wasn't in IE/Edge or else it would throw errors and that didn't seem like a good solution, so I just went with vanilla JS. Since your scripts get loaded in the HTML it would've been much more work than it was worth to do it and instead decided that vanilla JS was cleaner.

![image](https://user-images.githubusercontent.com/6969831/34183226-a65b7aaa-e4e7-11e7-9895-0442fe6b7ae8.png)

**Comment by cburkins** [comment]
@jfb74 Looks intriguing !   I'll check it out, and do a bit of smoke testing.

**Comment by cburkins** [comment]
@jfb74 Seems to work great !   A few new concepts in here, but I'm sure I'll get the hang of it.   When you're ready, create a pull request for your branch, and I'll merge it into the master

**Comment by cburkins** [comment]
@jfb74 Nice job writing the code for handling the chrome redirect.   It's well-documented, I appreciate that.
